kind: Pod
apiVersion: v1
metadata: 
    name: postgres-app
    labels:
        name: postgres-app
        app: demo-voting-app
spec:
    containers:
      - name: postgres     
        image: postgres
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_PASSWORD
            value: "postgres"  