kind: Service
apiVersion: v1
metadata: 
  name:  redis      
  labels:
    name: redis-server
    app: demo-voting-app
spec:
  ports: 
   - targetPort: 6379 
     port: 6379
  selector:
    name: redis-app
    app: demo-voting-app
