kind: Pod
apiVersion: v1
metadata: 
    name: voting-app
    labels:
        name: voting-app
        app: demo-voting-app
spec:
    containers:
      - name: voting-app
        image: israel9101/voting-app:v1
        ports:
          - containerPort: 80 