kind: Service
apiVersion: v1
metadata: 
  name:  result-service      
  labels:
    name: result-server
    app: demo-voting-app
spec:
  type: NodePort
  ports: 
   - targetPort: 80
     port: 80
     nodePort: 30005
  selector:
     name: result-app
     app: demo-voting-app
