kind: Deployment
apiVersion: apps/v1
metadata:
    name: redis-deployment
    labels:
      name: redis-deployment
      app: demo-voting-app
spec:
    selector:
      matchLabels:
        name: redis-app
        app: demo-voting-app
    template:
      metadata: 
          name: redis-app
          labels:
              name: redis-app
              app: demo-voting-app
      spec:
          containers:
            - name: redis
              image: redis
              ports:
                - containerPort: 6379 
    replicas: 1